name: Pip Dependency Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  pip-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies and check for version issues
        run: pip install -r requirements.txt
